esphome:
    name: livingroom
    comment: Living room ESP32 controller
    area: Living Room

external_components:
  - source: components

esp32:
    board: nodemcu-32s

uart:
  baud_rate: 115200
  tx_pin: 0
  rx_pin: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
      
viewsonic_projector_component:
  id: viewsonic_projector_1
